dfs:
  url: 94.191.83.120:8181
fdfs:
  connectTimeout: 600
  soTimeout: 1500
  thumbImage:
    height: 150
    width: 150
  trackerList:
    - 94.191.83.120:12050

spring:
  sleuth:
    sampler:
      percentage: 1.0
    web:
      client:
        enabled: true
  zipkin:
    #base-url: http://106.55.152.41:9411/
    sender:
      type: kafka
  cloud:
    stream:
      kafka:
        binder:
          brokers: 106.52.62.38:9092
  kafka:
    bootstrap-servers: 106.52.62.38:9092
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 106.52.62.38
    port: 6379
    password: 123456
    jedis:
      pool:
        max-wait: -1
        max-active: 100
        max-idle: 100
        min-idle: 10
  jmx:
    enabled: false
  rabbitmq:
    host: 94.191.83.120
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true
    virtual-host: /
  application:
    name: mall-web-order
  main:
    allow-bean-definition-overriding: true
shiro:
  maxAge:
    day: 10
sso:
  loginUrl: /api/system/unLogin
  client-id: c1ebe466-1cdc-4bd3-ab69-77c3561b9dee
  client-secret: d8346ea2-6017-43ed-ad68-19c0f971738b
  access-token-url: http://localhost:8180/mall-account/api/accessToken
  user-info-url: http://localhost:8180/mall-account/api/userInfo
  redirect-url: http://localhost:8180/mall-account/

company:
  images:
    login-logo: /assets/pc/images/login-logo.png
    logo: /assets/pc/images/logo.png
    login-bg: /assets/pc/images/login-bg.jpg
wx:
  appid: wxc5eae5bf209e986f
  appsecret:
  redirect_uri:

goods:
  pic:
    domain: http://demo5.tp-shop.cn

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8763/eureka/
    register-with-eureka: true
    fetch-registry: true
#instance:
  #hostname:
  #ip-address: 94.191.83.120
  #prefer-ip-address: true
  #instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000
          #信号量
          strategy: SEMAPHORE
          semaphore:
            # semaphore应该占整个容器（tomcat）的线程池的一小部分。
            maxConcurrentRequests: 800
      fallback:
        isolation:
          semaphore:
            # 只在信号量隔离策略中有效，建议设置大一些，这样并发数达到execution最大请求数时，会直接调用fallback，而并发数达到fallback最大请求数时会被拒绝和抛出异常。
            maxConcurrentRequests: 1000

#  threadpool:
#    default:
#      coreSize: 200 #并发执行的最大线程数，默认10
#      maxQueueSize: 1000 #BlockingQueue的最大队列数，默认值-1
#      queueSizeRejectionThreshold: 800 #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝，默认值5


ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 20000
  OkToRetryOnAllOperations: false
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  compression:
    request:
      enabled: true  #开启请求压缩功能
      mime-types: text/xml;application/xml;application/json #指定压缩请求数据类型
      min-request-size: 2048  #如果传输超过该字节，就对其进行压缩
    response:
      #开启响应压缩功能
      enabled:  true

logging:
  level:
    org:
      springframework:
        cloud:
          sleuth: debug