dfs:
  url: 94.191.83.120:8181
druid-master:
  jdbcUrl: jdbc:mysql://94.191.83.120:3309/order?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
  jdbcUrl1: jdbc:mysql://94.191.83.120:3310/order?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver
  minIdle: 2
  maxActive: 10
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  filters: stat,wall
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
druid-slave:
  url: jdbc:mysql://94.191.83.120:3308/mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver
  minIdle: 2
  maxActive: 10
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  filters: stat,wall
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

druid-mycat:
  jdbcUrl: jdbc:mysql://localhost:8066/orderdb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
  #jdbcUrl1: jdbc:mysql://94.191.83.120:3308/mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
  username: enjoy
  password: 123456
  driver-class-name: com.mysql.jdbc.Driver
  minIdle: 2
  maxActive: 10
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  filters: stat,wall
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


zookeeper:
  url: zookeeper://94.191.83.120:2181 #114.115.171.119

mybatis:
  mapper-locations: classpath*:mapping/**/*.xml
  config-location: classpath:SqlMapConfig.xml
spring:
  sleuth:
    sampler:
      percentage: 1.0
    web:
      client:
        enabled: true
  zipkin:
    #base-url: http://106.55.152.41:9411/
    sender:
      type: kafka
  cloud:
    stream:
      kafka:
        binder:
          brokers: 106.52.62.38:9092
    alibaba:
      seata:
        tx-service-group: pay_tx_group
  kafka:
    bootstrap-servers: 106.52.62.38:9092
  redis:
    host: 106.52.62.38
    port: 6379
    password: 123456
  application:
    name: mall-order-service
  data:
    mongodb:
      uri: mongodb://94.191.83.120:27017/mall
  datasource:
    initialize: false
  rabbitmq:
    host: 94.191.83.120
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true
    virtual-host: /
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@eureka.h:8763/eureka/
    register-with-eureka: true
    fetch-registry: true
    #instance:
    #hostname:
    #ip-address: 119.45.45.184
    #prefer-ip-address: true
    #instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 5000
  OkToRetryOnAllOperations: false
  MaxAutoRetriesNextServer: 0
  MaxAutoRetries: 0

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    cn:
      enjoy:
        mall:
          dao: debug
    org:
      springframework:
        cloud:
          sleuth: debug
#seata:
#  enabled: true
#  application-id: mall-pay
#  tx-service-group: pay_tx_group
#  enable-auto-data-source-proxy: true
#  use-jdk-proxy: false
#  excludes-for-auto-proxying: firstClassNameForExclude,secondClassNameForExclude
#  client:
#    rm:
#      async-commit-buffer-limit: 1000
#      report-retry-count: 5
#      table-meta-check-enable: false
#      report-success-enable: false
#      saga-branch-register-enable: false
#      lock:
#        retry-interval: 10
#        retry-times: 30
#        retry-policy-branch-rollback-on-conflict: true
#    tm:
#      degrade-check: false
#      degrade-check-period: 2000
#      degrade-check-allow-times: 10
#      commit-retry-count: 5
#      rollback-retry-count: 5
#    undo:
#      data-validation: true
#      log-serialization: jackson
#      log-table: undo_log
#      only-care-update-columns: true
#    log:
#      exceptionRate: 100
#  #  service:
#  #    vgroup-mapping:
#  #      pay_tx_group: default
#  #    grouplist:
#  #      default: 127.0.0.1:8091
#  #    enable-degrade: false
#  #    disable-global-transaction: false
#  transport:
#    shutdown:
#      wait: 3
#    thread-factory:
#      boss-thread-prefix: NettyBoss
#      worker-thread-prefix: NettyServerNIOWorker
#      server-executor-thread-prefix: NettyServerBizHandler
#      share-boss-worker: false
#      client-selector-thread-prefix: NettyClientSelector
#      client-selector-thread-size: 1
#      client-worker-thread-prefix: NettyClientWorkerThread
#      worker-thread-size: default
#      boss-thread-size: 1
#    type: TCP
#    server: NIO
#    heartbeat: true
#    serialization: seata
#    compressor: none
#    enable-client-batch-send-request: true
#  config:
#    type: file
#  registry:
#    redis:
#      server-addr: 106.52.62.38:6379
#      db: 0
#      password: 123456
#      timeout: 0
