dfs:
  url: 94.191.83.120:8181
fdfs:
    connectTimeout: 600
    soTimeout: 1500
    thumbImage:
        height: 150
        width: 150
    trackerList:
    - 94.191.83.120:12050

zookeeper:
  url: zookeeper://94.191.83.120:2181
spring:
  sleuth:
    sampler:
      percentage: 1.0
    web:
      client:
        enabled: true
  zipkin:
    #base-url: http://106.55.152.41:9411/
    sender:
      type: kafka
  cloud:
    stream:
      kafka:
        binder:
          brokers: 106.52.62.38:9092
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jmx:
    enabled: false
  application:
    name: mall-mng
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: 106.52.62.38:9092
  redis:
    host: 106.52.62.38
    port: 6379
    password: 123456
    jedis:
      pool:
        max-wait: -1
        max-active: 100
        max-idle: 100
        min-idle: 10
shiro:
  maxAge:
    day: 10
company:
  images:
    login-logo:
    logo:
    login-bg:
wx:
    appid: wxc5eae5bf209e986f
    appsecret:
    redirect_uri:

goods:
  pic:
    domain: http://demo5.tp-shop.cn

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@eureka.h:8763/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    #hostname:
    #ip-address: 94.191.83.120
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 20000
  OkToRetryOnAllOperations: false
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org:
      springframework:
        cloud:
          sleuth: debug